# Generated by Django 3.2.25 on 2025-07-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
    ]
