# Generated by Django 3.2.25 on 2025-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
