# Generated by Django 3.2.25 on 2025-07-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20250629_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
