# Generated by Django 3.2.25 on 2025-06-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='license_type',
            field=models.CharField(default='personal', max_length=20),
        ),
    ]
