# Generated by Django 3.2.25 on 2025-06-05 16:22

import avagen.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=avagen.storage_backends.GoogleCloudZipStorage(), upload_to='digital_downloads/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
