# Generated by Django 3.2.25 on 2025-06-05 16:59

import avagen.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_description'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldownload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='digitaldownload',
            name='file',
            field=models.FileField(max_length=500, storage=avagen.storage_backends.GoogleCloudZipStorage(), upload_to='digital_downloads/'),
        ),
        migrations.AlterField(
            model_name='digitaldownload',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_download', to='products.product'),
        ),
    ]
