# Generated by Django 3.2.25 on 2025-06-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20250626_0942'),
        ('catalogue', '0002_auto_20250605_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldownload',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_download', to='products.digitalproduct'),
        ),
    ]
