# Generated by Django 5.0.14 on 2025-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
