# Generated by Django 3.2.25 on 2025-06-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_license_number_product_model_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
