# Generated by Django 3.2.25 on 2025-06-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderlineitem_product'),
        ('catalogue', '0003_alter_digitaldownload_product'),
        ('products', '0018_auto_20250626_0942'),
        ('reviews', '0003_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
