# Generated by Django 3.2.25 on 2025-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20250626_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='is_creator_product',
        ),
    ]
